config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  get "/home" => "home#index"
  get "/home/about" => "home#about"

  resources :tasks
 match '/tasks/:id/done' => 'tasks#done', as: 'done_task', via: :put

end

app/models/task.rb
class Task < ActiveRecord::Base
scope:done, -> {where(done:1)}
scope:pending, -> {where(done:0)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks - List the tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/:id - Display a particular task
  def show
  end

  # GET /tasks/new - Load the form for creating a new task
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit - Edit a task
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    
      if @task.save
         @task.done=0
         @task.save
        redirect_to @task, notice: 'Task was successfully created.' 
      
      else
        format.html render :new 
       
      end
    
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task has been updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

 #PUT /tasks/1/done
 def done

 @task= Task.find(params[:id])
 @task.done=1
 @task.save
 redirect_to @task,notice:'Task has been marked as done.'
 end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task has been Deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_name, :date, :priority, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/about.html.erb
<h4>Simple To Do Application</h4>
<p>Created by Rewath Kafley,<br/> as a part of an Assignment...</p>

app/views/home/index.html.erb
<h3> A simple Rails application to manage your to do tasks</h3>
<br/>
<h4>Features</h4>
<ul>
<li>Create to do tasks with priority</li>
<li>Edit and delete tasks</li>
<li>Mark a task as done</li>
</ul>

<h4>Development time(without prior ruby knowledge)</h4>
<ul>
<li>One Week</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <title>A Simple To Do Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="UTF-8">
</head>
<body>
<section id="menu">
<h1>A Simple Rails Application</h1>
<hr/>
<ul>

<li><a href="/">Home</a></li>
<li><a href="/tasks">Tasks</a></li>
<li><a href="/home/about">About</a></li>



</ul>

</section>
<section id="content">
<%= yield %>
</section>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_name %><br>
    <%= f.text_field :task_name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :priority %>(1-5)<br>
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Tasks &nbsp;&nbsp; </h1>
<div style="border-bottom:2px solid black;width:720px"></div>
<br/>
<%= link_to 'New Task', new_task_path %>
<h3>Completed Tasks</h3>
<table border=1 cellspacing=0>
  <thead>
    <tr>
      <th>Task name</th>
      <th>Date</th>
      <th>Priority</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.done.each do |task| %>
      <tr>
        <td><%= task.task_name %></td>
        <td><b>Date: </b><%= task.date.strftime("%A %b %d,%Y") %>
        <br/>
        <b>Time: </b><%= task.date.strftime("%I:%M:%S %p") %>
        </td>
        <td><%= task.priority %></td>
        <td><%= task.description %></td>
        <td><%= link_to 'Details', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task),method: :put %></td>
        <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
      </tr>
    <% end %>
  </tbody>
</table>


<h3>Pending Tasks</h3>
<table border=1 cellspacing=0>
  <thead>
    <tr>
      <th>Task name</th>
      <th>Date</th>
      <th>Priority</th>
      <th>Description</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.pending.each do |task| %>
      <tr>
        <td><%= task.task_name %></td>
        <td><b>Date: </b><%= task.date.strftime("%A %b %d,%Y") %>
        <br/>
        <b>Time: </b><%= task.date.strftime("%I:%M:%S %p") %>
        </td>
        <td><%= task.priority %></td>
        <td><%= task.description %></td>
        <td><%= link_to 'Details', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task),method: :put %></td>
        <td><%= link_to 'Mark as Done' , done_task_path(task),method: :put %></td>
        <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
      </tr>
    <% end %>
  </tbody>
</table>


<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task name:</strong>
  <%= @task.task_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @task.date.strftime("%A %b %d,%Y %I:%M:%S %p") %>
 </p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>